### ISSUE TITLE
Cant  import sql

### ISSUE THREAD

**Issue by davvvve1** [bewarellamas/mod-dungeonmaster#4]
Cant import the sql file ;(

**Comment by bewarellamas** [comment]
Do you have any error information? Is it failing for both files for just one?

**Comment by Sundarkdk** [comment]
the sql file to add the npc has entries for modelid1 to 4, but table in the database dont has this fields, i fixed deleting this fields and values in sql file, but now server can´t load  npc couse no model id assigned in creature_template_model.

Creature (Entry: 197762) has no model defined in table `creature_template_model`, can't load.

this is my azerothcore version:
AzerothCore rev. 1294d79764e3 2024-11-25 23:22:31 +0800 (Playerbot branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)

added data missing and now all work fine...

**Comment by davvvve1** [comment]
Only for one file . When I tried another fork it worked . But i ditched dbeaver on Linux and changed to dbgate, mabye thats was the problem.

**Comment by bewarellamas** [comment]
[dungeon_npc.txt](https://github.com/user-attachments/files/17979698/dungeon_npc.txt)

Looks like this wasn't updated for the new creature db schema. I attached an updated SQL file (will need to be renamed from txt to sql if you use it that way. Site won't let me upload .sql files). Give it a try and let me know the result and I I can update the repo.

**Comment by Sundarkdk** [comment]
The new sql file works fine for me...

**Comment by bewarellamas** [comment]
#5
